### ISSUE TITLE
Configuring the gateway using .Gateway() blows up

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Gateway#67]
To repro run the [gateway sample](https://docs.particular.net/samples/gateway/) but change `endpointConfiguration.EnableFeature<Gateway>()` to `endpointConfiguration.Gateway()`

the endpoint will now blow up with
<details>

```
Autofac.Core.DependencyResolutionException was unhandled
  HResult=-2146233088
  Message=None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'NServiceBus.Installation.GatewayHttpListenerInstaller' can be invoked with the available services and parameters:
Cannot resolve parameter 'NServiceBus.Gateway.Receiving.IManageReceiveChannels channelManager' of constructor 'Void .ctor(NServiceBus.Gateway.Receiving.IManageReceiveChannels, Boolean)'.
  Source=NServiceBus.Core
  StackTrace:
       at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\IncomingMessage.cs:line 0
       at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\IncomingMessage.cs:line 0
       at Autofac.Core.Resolving.InstanceLookup.Execute() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\IncomingMessage.cs:line 0
       at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\IncomingMessage.cs:line 0
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at Autofac.Features.Collections.CollectionRegistrationSource.<>c__DisplayClass4.<RegistrationsFor>b__0(IComponentContext c, IEnumerable`1 p) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\IncomingMessage.cs:line 0
       at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\IncomingMessage.cs:line 0
       at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\IncomingMessage.cs:line 0
       at Autofac.Core.Resolving.InstanceLookup.Execute() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\IncomingMessage.cs:line 0
       at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\IncomingMessage.cs:line 0
       at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\IncomingMessage.cs:line 0
       at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\IncomingMessage.cs:line 0
       at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\IncomingMessage.cs:line 0
       at NServiceBus.AutofacObjectBuilder.ResolveAll(IComponentContext container, Type componentType) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\ObjectBuilder\Autofac\AutofacObjectBuilder.cs:line 180
       at NServiceBus.CommonObjectBuilder.BuildAll[T]() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\ObjectBuilder\Common\CommonObjectBuilder.cs:line 48
       at NServiceBus.InitializableEndpoint.<RunInstallers>d__13.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\InitializableEndpoint.cs:line 164
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NServiceBus.InitializableEndpoint.<Initialize>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\InitializableEndpoint.cs:line 58
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NServiceBus.Endpoint.<Start>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Endpoint.cs:line 27
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
       at Program.<AsyncMain>d__1.MoveNext() in C:\Users\andreas.ohlund\Downloads\gateway_gateway_2\Headquarters\Program.cs:line 24
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Program.Main() in C:\Users\andreas.ohlund\Downloads\gateway_gateway_2\Headquarters\Program.cs:line 11
  InnerException: 

```
</details>

Looking at the code I think we just need to add a call to `.EnableFeature<Gateway>()` in https://github.com/Particular/NServiceBus.Gateway/blob/develop/src/NServiceBus.Gateway/Settings/GatewayExtensions.cs#L14

**Comment by danielmarbach** [comment]
Yes and probably also refactor existing tests to use that extension method

https://github.com/Particular/NServiceBus.Gateway/search?utf8=%E2%9C%93&q=EnableFeature

**Comment by andreasohlund** [comment]
And also the sample

**Comment by andreasohlund** [comment]
Fixed in https://github.com/Particular/NServiceBus.Gateway/pull/72

**Comment by andreasohlund** [comment]
Will deal with the sample in https://github.com/Particular/docs.particular.net/issues/3139
